# Generated by Django 2.2.2 on 2019-07-02 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=30)),
                ('reset_code', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('path', models.TextField()),
                ('downloaded', models.TextField(max_length=30)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=270)),
                ('experience', models.IntegerField()),
                ('location', models.TextField(max_length=30)),
                ('profile_type', models.TextField()),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cvapp.Users')),
            ],
        ),
    ]
