# Generated by Django 2.2.2 on 2019-07-02 05:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.TextField()),
                ('designation', models.CharField(max_length=255)),
                ('experience', models.DecimalField(decimal_places=2, max_digits=3)),
                ('location', models.TextField(null=True)),
                ('profile_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'requirements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_name', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('filepath', models.FileField(upload_to='')),
                ('extension', models.CharField(max_length=255)),
                ('filesize', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'uploads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reset_code', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='actor_id',
        ),
        migrations.DeleteModel(
            name='Requirements',
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='upload',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads_actor', to='cvapp.User'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_actor', to='cvapp.User'),
        ),
    ]
