# Generated by Django 2.2.2 on 2019-07-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_auto_20190702_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='filepath',
            field=models.FileField(upload_to='media/'),
        ),
    ]
