# Generated by Django 3.0.6 on 2020-05-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('time', models.CharField(max_length=22)),
            ],
            options={
                'verbose_name': 'music',
                'ordering': ['auteur'],
            },
        ),
    ]
